spring:
  datasource:
#    url: jdbc:mysql://10.3.174.129:3306/study&skill?useUnicode=true&characterEncoding=utf8
#    username: othernet
#    password: other_net1
    url: jdbc:mysql://localhost:3306/studyskill?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 10MB
  resources:
    static-locations: classpath:static/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: studyskill.entity

server:
  port: 8999